#' Title
#'
#' @param D2C_matrix The drug-by-cell matrix generated by DrugReSC
#' @param cell_labels The cell phenotype labels
#'
#' @return The raw drug scores
#' @export
#'
#' @importFrom stats wilcox.test
cal_wilcoxon_drug_score <- function(D2C_matrix,cell_labels){
  print("Running analysis of wilcoxon rank-sum test")
  zero_rows <- which(apply(D2C_matrix, 1, function(x) all(x == 0)))
  if(length(zero_rows) != 0){
    D2C_matrix <- D2C_matrix[-zero_rows,]
  }
  C2D_matrix <- as.data.frame(t(D2C_matrix))
  p_values <- apply(C2D_matrix, 2, function(feature) wilcox.test(feature[cell_labels==0], feature[cell_labels==1])$p.value)
  sc_predict <- -p_values
  return(sc_predict)
}
