#' Title
#'
#' @param D2C_matrix The drug-by-cell matrix generated by DrugReSC
#' @param cell_labels The cell phenotype labels
#' @param ncore The number of parallel threads
#'
#' @return The raw drug scores
#' @export
#'
#'@importFrom parallel makeCluster
#'@importFrom parallel clusterEvalQ
#'@importFrom parallel parSapply
#'@importFrom parallel stopCluster
#'@importFrom randomForest randomForest
#'@importFrom randomForest importance
#'

cal_rf_drug_score <- function(D2C_matrix,cell_labels,ncore){
  print("Running random forest")
  zero_rows <- which(apply(D2C_matrix, 1, function(x) all(x == 0)))
  if(length(zero_rows) != 0){
    D2C_matrix <- D2C_matrix[-zero_rows,]
  }
  tmp_matrix <- data.frame()
  tmp_matrix <- as.data.frame(t(D2C_matrix))
  cell_labels <- as.factor(cell_labels);gc()
  cl <- makeCluster(ncore)
  clusterEvalQ(cl, library(randomForest))
  err=NULL
  err <- parSapply(cl, 1:ncol(tmp_matrix), function(j){
    mtry_test <- randomForest(x = tmp_matrix,
                              y = cell_labels,
                              mtry = j,
                              ntree = 100)
    return(mean(mtry_test$err.rate))
  })
  stopCluster(cl)
  best_error <- which.min(err)
  rf <- randomForest(cell_labels ~ ., data = tmp_matrix, ntree= 100, mtry=best_error, importance = TRUE)
  sc_predict <- importance(rf)[,1]
  return(sc_predict)
}
