#' Title
#'
#' @param D2C_matrix  The drug-by-cell matrix generated by DrugReSC
#' @param cell_labels The cell phenotype labels
#'
#' @return The raw drug scores
#' @export
#'
#'@importFrom glmnet cv.glmnet
#'@importFrom glmnet glmnet
#'@importFrom stats coef


cal_lgr_drug_score <- function(D2C_matrix,cell_labels){
  print("Running logistic regression")
  zero_rows <- which(apply(D2C_matrix, 1, function(x) all(x == 0)))
  if(length(zero_rows) != 0){
    D2C_matrix <- D2C_matrix[-zero_rows,]
  }
  mod_cv <- cv.glmnet(as.matrix(t(D2C_matrix)), as.factor(cell_labels), family="binomial", nfolds = 5)
  best_lambda <- mod_cv$lambda.min
  fit.full <- glmnet(as.matrix(t(D2C_matrix)), as.factor(cell_labels), family="binomial",  lambda = best_lambda)
  coefficients <- coef(fit.full)
  sc_predict <- -coefficients[-1,1]
  return(sc_predict)
}
