#' Title
#'
#' @param D2C_matrix  The drug-by-cell matrix generated by DrugReSC
#' @param cell_labels The cell phenotype labels
#'
#' @return The raw drug scores
#' @export
#'
#'@importFrom stats bartlett.test
#'@importFrom stats oneway.test
#'

cal_aov_drug_score <- function(D2C_matrix,cell_labels){
  print("Running analysis of variance")
  zero_rows <- which(apply(D2C_matrix, 1, function(x) all(x == 0)))
  if(length(zero_rows) != 0){
    D2C_matrix <- D2C_matrix[-zero_rows,]
  }
  variance <- NULL
  variance <- apply(D2C_matrix, 1, function(x){
    bartlett.test(x, cell_labels)$p.value
  })
  sc_predict <- NULL
  for (i in 1:length(variance)) {
    if(is.na(variance[i])){
      sc_predict[i] <- 0
    }else if(variance[i] < 0.05){
      sc_predict[i] <- oneway.test(D2C_matrix[i,]~cell_labels, var.equal = FALSE)$statistic
    }else{
      sc_predict[i] <- oneway.test(D2C_matrix[i,]~cell_labels, var.equal = T)$statistic
    }
  }
  return(sc_predict)
}
