#' Title
#'
#' @param D2C_matrix The drug-by-cell matrix generated by DrugReSC
#' @param cell_labels The cell phenotype labels
#'
#' @return The raw drug scores
#' @export
#'
#' @importFrom rminer fit
#' @importFrom rminer Importance

cal_svm_drug_score <- function(D2C_matrix,cell_labels){
  print("Running support vector machine")
  zero_rows <- which(apply(D2C_matrix, 1, function(x) all(x == 0)))
  if(length(zero_rows) != 0){
    D2C_matrix <- D2C_matrix[-zero_rows,]
  }
  data <- cbind(as.data.frame(t(D2C_matrix)),cell_labels=as.factor(cell_labels))
  svm_model <- fit(cell_labels ~ ., data = data, model="ksvm",type = "C-svc", kernel = 'rbfdot')
  sc_predict <- Importance(svm_model, data = data[,-ncol(data)], method="1D-SA")[["imp"]]
  return(sc_predict)
}
